[phases.setup]
nixPkgs = ['nodejs_20', 'npm-10_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npx prisma generate', 'npm run build', 'npx prisma migrate deploy']

[start]
cmd = 'npm run start:prod'
